[package]
name = "clap-sh"
version = "0.1.0"
edition = "2024"


[lib]
name = "clap_sh" # Users will use 'use my_tool_lib;'
path = "src/lib.rs"

[[bin]]
name = "clapsh"
path = "src/main.rs"


[dependencies]
pretty-hex = "0.4.1"
thiserror = "2.0.18"
